### ISSUE TITLE
UCP: Add backoff and retry limit to requests

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-rust#110]
## Description

We shouldn't allow infinite or immediate retries. It is better to add backoff retry delay.

## Difficulty
- Easy

## Score
- 50

## Mentor(s)
- @sticnarf 
- @nrc

## Recommended Skills
- Rust

**Comment by silathdiir** [comment]
Hi @sticnarf, I'd like to fix this issue. I tried to do some search for `retry`.
It seems that the file `src/pd/retry.rs` already has the logic and constants for `reconnect`.

```
const RECONNECT_INTERVAL_SEC: u64 = 1;
const MAX_REQUEST_COUNT: usize = 3;
const LEADER_CHANGE_RETRY: usize = 10;
```

Could you give some instructions on this? Thanks.

**Comment by sticnarf** [comment]
@silathdiir Yes, you're right. The PD client will retry only a few times on failures .

However, when there is a "region error", we will retry immediately and for unlimited times: https://github.com/tikv/client-rust/blob/master/src/request.rs#L85

I'm really happy you can help fix it :)
