### ISSUE TITLE
UCP: Add region cache for PD

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-rust#114]
## Description
It costs too much if we query PD for region information in every request. We can save region information in cache and query if necessary (on region error or the region for the key is unknown)

It's a good to idea to use the TiDB implementation as a reference: https://github.com/pingcap/tidb/blob/master/store/tikv/region_cache.go

@nrc has a PR which gives an incomplete implementation: https://github.com/tikv/client-rust/pull/121. You can continue that PR as well.

## Difficulty
- Medium

## Score
- 3000

## Mentor(s)
- @sticnarf 
- @nrc 

## Recommended Skills
- Rust
- TiKV Architecture

**Comment by SSebo** [comment]
@sticnarf Could you explain a little bit what is the difficult part of this issue? 3000 points is really high.

**Comment by sticnarf** [comment]
@SSebo This task is not just porting the region cache implementation. The difficulty here is the associating request error handling with cache manipulation.

So if you want to try this task, you may not only look at the region cache in TiDB itself, but also how the cache is used and refreshed on errors.

**Comment by SSebo** [comment]
@sticnarf I'll have a try after I got my 200 points. Hope this issue is unpick until then.

**Comment by SSebo** [comment]
Is there any resources that should read before pick this issue?

**Comment by sticnarf** [comment]
> Is there any resources that should read before pick this issue?

I'm sorry but I don't know any text resource about it. TiDB code https://github.com/pingcap/tidb/blob/master/store/tikv/region_cache.go and https://github.com/pingcap/tidb/blob/master/store/tikv/region_request.go may be helpful but you don't necessarily copy the exact implementation of TiDB.

**Comment by SSebo** [comment]
unformally picked up

**Comment by SSebo** [comment]
@sticnarf  Can I continue nrc's work? I just merge nrc `region-cache` branch to `master`, Could you reopen that PR?

**Comment by sticnarf** [comment]
@SSebo I've reopened it.

**Comment by SSebo** [comment]
@sticnarf bot close It again, I'll wait until my easy PR merged
