### ISSUE TITLE
Add into_inner function to Key, Value and KvPair

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-rust#12]
It provides a way of getting the ownership of the inner Vec. It saves one clone when we need the ownership of the data.

An alternative is to implement `From<Key>` and  `From<Value>` for `Vec<u8>`. But I prefer the `into_inner` way.

By the way, is `[u8]` a better choice for the deref target of `Key` and `Value`? `[u8]` is just a more common deref target in the Rust world. `Vec` is ok but less comfortable to me and does no good too (I think no one cares about the only addition `capacity`). This is really of no significance, so I do not open a new issue.

**Comment by sunxiaoguang** [comment]
I agree with you that the into_inner way is preferable. BTW: Did you mean From<Key> for Vec<u8>?
I also agree [u8] could be a better choice for Deref target. Let's see if there are more comments.

**Comment by sticnarf** [comment]
Ah, yes, that's a mistake. Fixed now. Thanks.
