### ISSUE TITLE
UCP: Add backoff and retry limit to lock resolving

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-rust#135]
## Description

Now we use a fixed delay before resolving locks. It is better to add backoff retry delay and retry limit.

The task is to resolve the TODO here:
https://github.com/tikv/client-rust/blob/f3f3db349cf4131642baa83c3977490bcc7364c7/src/request.rs#L65

## Difficulty
- Easy

## Score
- 50

## Mentor(s)
- @sticnarf 
- @nrc

## Recommended Skills
- Rust

**Comment by you06** [comment]
@silathdiir Dear contributor, we will close the issue if there is no update in 7 days.

**Comment by silathdiir** [comment]
@you06 I am sorry that I am busy on these days. Will get back to work on this in this week.

**Comment by you06** [comment]
@silathdiir Don't worry about it, our [rules](https://github.com/pingcap/community/blob/master/challenge-programs/challenge-program-season-2-cn.md#%E7%AC%AC%E4%BA%8C%E6%AD%A5%E9%A2%86%E5%8F%96%E4%BB%BB%E5%8A%A1) have just been updated

**Comment by you06** [comment]
@silathdiir sorry for this accident, the pick for you is recovered.
