### ISSUE TITLE
Transactional API

### ISSUE THREAD

**Issue by Hoverbear** [tikv/client-rust#15]
In #14 we enabled the Raw client, and scaffolded much of the code needed for the transactional client. This issue tracks the completion of the first release of the Transactional API.

In order to close this issue you'll need to replace all `unimplemented!()` in the `src/transaction.rs` file with working code. You can reference the `src/raw.rs` code to help with this, however transactions are quite a bit more complicated than the raw client.

**Comment by Kerollmops** [comment]
I would like to use this client but I will need the transaction API for that. Would it be possible to add some hints about where to find the current go transaction implementation if any?

I am currently [searching in the tidb repository with github](https://github.com/pingcap/tidb/search?p=4&q=Begin&unscoped_q=Begin) but it is hard to find anything interresting...

**Comment by sunxiaoguang** [comment]
> I would like to use this client but I will need the transaction API. Would it be possible to add some hints about where to find the current go transaction implementation if any?
> 
> I am currently [searching in the tidb repository with github](https://github.com/pingcap/tidb/search?p=4&q=Begin&unscoped_q=Begin) but it is hard to find anything interresting...
> 
> I also find [the kv directory in tidb](https://github.com/pingcap/tidb/tree/master/kv) but it seems that there only is the go `Storage interfaces`, no code related to the transaction aquierement.
> 
> Ok, so I found the implementation in [tidb/store/tikv/kv.go](https://github.com/pingcap/tidb/blob/master/store/tikv/kv.go) and [tidb/store/tikv/txn.go](https://github.com/pingcap/tidb/blob/master/store/tikv/txn.go).

There is on going work to move TiKV client out of TiDB code base. [You can take a look at it.](https://github.com/tikv/client-go)

**Comment by Kerollmops** [comment]
Thank you for the link @sunxiaoguang but it doesn't show me how I can implement the transactional Rust client so I fallback on the previous links I posted.

Would it be possible to have some kind of mentoring?

I saw that the `transaction::Client::begin` method could follow [the steps of the Go client](https://github.com/pingcap/tidb/blob/63936cc1fa8dbfea793b90a0cf1d78312354a141/store/tikv/kv.go#L254-L261) by [creating a new TiKV transaction](https://github.com/pingcap/tidb/blob/63936cc1fa8dbfea793b90a0cf1d78312354a141/store/tikv/txn.go#L50-L57).

I do not know how to retrieve the snapshot based on the timestamp like the Go function do.
I found the `rpc::client::txn` function which, based on a key, return a `TxnContext`.
Internally it [use the `key` to locate in which "region" it is](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/client.rs#L194-L210), is it useful for me to implement the transactional client?

This `TxnContext` could be used to call [functions prefixed by `kv_`](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/tikv/client.rs#L277-L297) present in the `rpc/tikv/client.rs` are related to transactions. These functions need to specify the `version` at which the transaction must run, is this something related to the RocksDB `timestamp/snapshot`?

The only way I found [to retrieve a `version/timestamp` is highly related to the `TxnContext/Region`](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/pd/mod.rs#L103).

**Comment by sunxiaoguang** [comment]
> Thank you for the link @sunxiaoguang but it doesn't show me how I can implement the transactional Rust client so I fallback on the previous links I posted.
> 
> Would it be possible to have some kind of mentoring?
> 
> I saw that the `transaction::Client::begin` method could follow [the steps of the Go client](https://github.com/pingcap/tidb/blob/63936cc1fa8dbfea793b90a0cf1d78312354a141/store/tikv/kv.go#L254-L261) by [creating a new TiKV transaction](https://github.com/pingcap/tidb/blob/63936cc1fa8dbfea793b90a0cf1d78312354a141/store/tikv/txn.go#L50-L57).
> 
> I do not know how to retrieve the snapshot based on the timestamp like the Go function do.
> I found the `rpc::client::txn` function which, based on a key, return a `TxnContext`.
> Internally it [use the `key` to locate in which "region" it is](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/client.rs#L194-L210), is it useful for me to implement the transactional client?
> 
> This `TxnContext` could be used to call [functions prefixed by `kv_`](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/tikv/client.rs#L277-L297) present in the `rpc/tikv/client.rs` are related to transactions. These functions need to specify the `version` at which the transaction must run, is this something related to the RocksDB `timestamp/snapshot`?
> 
> The only way I found [to retrieve a `version/timestamp` is highly related to the `TxnContext/Region`](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/pd/mod.rs#L103).

Although we haven't reached final design of transactional API yet. You may find more about the internal implementation detail from [client-go](https://github.com/tikv/client-go). It involves many implementation details had is probably very hard to describe in couple of sentences. BTW: Maybe reading google percolator paper could help you a lot understanding TiKV's transaction model.

**Comment by sunxiaoguang** [comment]
> Thank you for the link @sunxiaoguang but it doesn't show me how I can implement the transactional Rust client so I fallback on the previous links I posted.
> 
> Would it be possible to have some kind of mentoring?
> 
> I saw that the `transaction::Client::begin` method could follow [the steps of the Go client](https://github.com/pingcap/tidb/blob/63936cc1fa8dbfea793b90a0cf1d78312354a141/store/tikv/kv.go#L254-L261) by [creating a new TiKV transaction](https://github.com/pingcap/tidb/blob/63936cc1fa8dbfea793b90a0cf1d78312354a141/store/tikv/txn.go#L50-L57).
> 
> I do not know how to retrieve the snapshot based on the timestamp like the Go function do.
> I found the `rpc::client::txn` function which, based on a key, return a `TxnContext`.
> Internally it [use the `key` to locate in which "region" it is](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/client.rs#L194-L210), is it useful for me to implement the transactional client?
> 
> This `TxnContext` could be used to call [functions prefixed by `kv_`](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/tikv/client.rs#L277-L297) present in the `rpc/tikv/client.rs` are related to transactions. These functions need to specify the `version` at which the transaction must run, is this something related to the RocksDB `timestamp/snapshot`?
> 
> The only way I found [to retrieve a `version/timestamp` is highly related to the `TxnContext/Region`](https://github.com/tikv/client-rust/blob/c47b92bab43945bc8766b6d5ad2f9c4d6887808a/src/rpc/pd/mod.rs#L103).

In case I didn't make it clear. The transactional part has lots of work at client side, it's probably different from what people normally think about implementing transactional api for relational databases. Although reading a paper sounds like too much, but I'm afraid that's probably the most efficient way to understand it.

**Comment by brson** [comment]
Thanks @sunxiaoguang for the pointers.

cc @nrc here's some important work going on that might be notable to you.

**Comment by howaboutsynergy** [comment]
Hi. Is it safe to assume that when this issue is closed(aka transactional API is implemented) then this [transactional example](https://github.com/tikv/client-rust/blob/e97407a81748dbee1151ec10707f982d1e078e0b/examples/transaction.rs#L28) will not panic with `panicked at 'not yet implemented', /home/user/build/2nonpkgs/rust.stuff/client-rust/src/transaction/transaction.rs:113:9` ? Thanks.

**Comment by nrc** [comment]
> Hi. Is it safe to assume that when this issue is closed(aka transactional API is implemented) then this transactional example will not panic with panicked at 'not yet implemented'

Yes, for sure

**Comment by nrc** [comment]
THis is basically implemented now and can be better tracked with more precise issues
