### ISSUE TITLE
get_for_update does not release lock after rollback

### ISSUE THREAD

**Issue by Hexilee** [tikv/client-rust#216]
### A minimal reproducible example
> - client-rust version: [#2d657d](https://github.com/tikv/client-rust/commit/2d657d74bead801786733f61293ecab94e50c52d)
> - rust toolchain: nightly-2020-10-19-x86_64-unknown-linux-gnu
> - tikv version: 4.1.0-alpha Community d9df87badf18ca5262cecaf02520a7099e7ae3da
```rust
use tikv_client::{TransactionClient, Error, Transaction};

#[async_std::main]
async fn main() -> Result<(), Error> {
    let client = TransactionClient::new_with_config(vec!["127.0.0.1:2379"], Default::default()).await?;
    let mut preload_txn = client.begin_optimistic().await?;
    let key = vec![1];
    let value = key.clone();

    preload_txn.put(key.clone(), value).await?;
    preload_txn.commit().await?;
    loop {
        let mut txn = client.begin_pessimistic().await?;
        let result = get_for_update(&mut txn, key.clone()).await;
        txn.rollback().await?;
        result?;
    }
}

async fn get_for_update(txn: &mut Transaction, key: Vec<u8>) -> Result<(), Error> {
    txn.get_for_update(key).await?.unwrap();
    Ok(())
}
```

Execute `cargo run` then you will get an error: 

```rust
KeyError(KeyError { locked: Some(LockInfo { primary_lock: [1], lock_version: 422032712969486340, key: [1], lock_ttl: 3000, txn_size: 0, lock_type: PessimisticLock, lock_for_update_ts: 422032712969486341, use_async_commit: false, min_commit_ts: 0, secondaries: [] }), retryable: "", abort: "", conflict: None, already_exist: None, deadlock: None, commit_ts_expired: None, txn_not_found: None, commit_ts_too_large: None })
```

**Comment by nrc** [comment]
@ekexium could you take a look at this please?

**Comment by ekexium** [comment]
/assign
Sure

**Comment by ekexium** [comment]
It's caused by the problematic implementation of `get_for_udpate`. It doesn't record the pessimistic lock in the local buffer, so the rollback command won't rollback the key.

I suggest we keep the same (or similar) semantics with TiDB: use the pessimistic lock request to read the value. 

The problem is that the response cannot tell us it's an empty value or it's non-existent. But existing code depends on the fact that we distinguish them.

**Comment by nrc** [comment]
@ekexium sgtm, do you have time to implement this?

**Comment by ekexium** [comment]
@nrc WIP. I found another bug related with it. I will fix them together.

**Comment by Hexilee** [comment]
This bug seems to be fixed.
