### ISSUE TITLE
Automatically send heartbeats

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#227]
For long-running transactions, the client should send heartbeat messages to the server. This should be optional (similar to retrying) and on by default. It should still be possible to manually send heartbeats.

**Comment by andylokandy** [comment]
Copied from https://github.com/tikv/client-rust/pull/221#issuecomment-759911420:

> For the heartbeat api, I think there is one question that we have to answer: in what situation, when the user holds a valid (not crashed and network's good) client and txn, we'd like the txn to be rollbacked?
> 
> If no scenario is found, the heartbeat api should be completely behind the scene.

**Comment by nrc** [comment]
> If no scenario is found, the heartbeat api should be completely behind the scene.

My philosophy for the client is that the default API should make things as easy as possible for the user and so things like heartbeats and retries should happen automatically. However, it should be possible to customise the workflow up to the level of the gRPC API. The use cases here are for somebody re-implementing TiDB in Rust, or more likely implementing some other, equally complex, DB on top of TiKV, or using the Rust client to automatically test edge cases in TiKV where we might want to simulate missing heart beats or heart beats which are out of order or duplicated or have incorrect timestamps or whatever.

**Comment by TszKitLo40** [comment]
Where the API should be added in the `rust-client`?

**Comment by ekexium** [comment]
@TszKitLo40 You can add a field in `TransactionOptions`

**Comment by TszKitLo40** [comment]
> TransactionOptions
Do you mean it should be a `bool`  to indicate whether is will send heartbeats automatically? But where should the API be added?

**Comment by ekexium** [comment]
@TszKitLo40 I think it can be a bool.
The interface should be the `TransactionOptions` that users supply. Do you mean where to implement it? One initial idea is to make use of the `bg_worker`.

**Comment by TszKitLo40** [comment]
> @TszKitLo40 I think it can be a bool.
> The interface should be the `TransactionOptions` that users supply. Do you mean where to implement it? One initial idea is to make use of the `bg_worker`.

Yes, I mean where to implement this API. Do you mean we should implement it as a method in the `Client` in `transaction/client.rs` and make use of `bg_worker`?

**Comment by ekexium** [comment]
@TszKitLo40 
Heartbeats are for transactions, so I think it shouldn't be implemented in `Client`. 
Each transaction has its `TransactionOptions` which is the place that users can specify the behavior.
I think we can start periodically sending heartbeats since one transaction starts, and stop when the transaction is rolled back or committed. It can be implemented in `transaction.rs`, I guess.

**Comment by TszKitLo40** [comment]
> @TszKitLo40
> Heartbeats are for transactions, so I think it shouldn't be implemented in `Client`.
> Each transaction has its `TransactionOptions` which is the place that users can specify the behavior.
> I think we can start periodically sending heartbeats since one transaction starts, and stop when the transaction is rolled back or committed. It can be implemented in `transaction.rs`, I guess. Note that manually sending heartbeats is already implemented in `Transaction`.

Should we also define a variable for the heartbeat interval?

**Comment by ekexium** [comment]
@TszKitLo40 
Yes there should be a constant variable for the default interval.
Personally I don't think it needs to be configurable (for now).

**Comment by TszKitLo40** [comment]
I want to start periodically sending heartbeats in the `new method` of Transaction. And it seems that the `bg_worker` which is a `ThreadPool` can't be executed at a fixed rate, any example for me to refer?

**Comment by ekexium** [comment]
How about spawning a task that periodically do something in the thread pool?

**Comment by TszKitLo40** [comment]
When should we spawn the task? Should we distinguish the optimistic lock and pessimistic lock? @ekexium

**Comment by ekexium** [comment]
@TszKitLo40 Similar to TiDB, after the prewrite, and after each pessimistic lock acquisition.
