### ISSUE TITLE
Fix the jitter tests

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#240]
For some reason the jitter tests fail on CI some or most of the time but consistently pass locally (at least for me, on both Mac and Linux).

**Comment by longfangsong** [comment]
IMO the jitter tests are supposed to panic:
```rust
#[should_panic(expected = "base_delay_ms must be positive")]
```

The real failed test in #236 is `failpoints_tests::optimistic_heartbeat`

**Comment by longfangsong** [comment]
PS. 
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/13777628/109758141-14882400-7c26-11eb-85c1-238458ac3cac.png">

We should migrate from travis to other CI platforms, maybe GitHub Action.
