### ISSUE TITLE
Some errors are not propagated out

### ISSUE THREAD

**Issue by ekexium** [tikv/client-rust#242]
https://github.com/tikv/client-rust/blob/3fad149ff31448288093a54288dd0e7688c3ad89/tikv-client-store/src/errors.rs#L153-L157

The implementation ignores `Err`, which will cause problems, e.g. we turn `error` to `Err` in `MultiRegion` and following plans will not be able to detect the error using `HasError::error`.

Even if the errors get propagated, we sometimes ignore them. For example, if the response contains errors, following commands can still succeed.
https://github.com/tikv/client-rust/blob/3fad149ff31448288093a54288dd0e7688c3ad89/src/transaction/transaction.rs#L943-L952
and 
https://github.com/tikv/client-rust/blob/3fad149ff31448288093a54288dd0e7688c3ad89/src/transaction/transaction.rs#L1008

**Comment by nrc** [comment]
cc #238
