### ISSUE TITLE
`send_heart_beat` does not update TTL

### ISSUE THREAD

**Issue by ekexium** [tikv/client-rust#243]
The TTL should be `(current_time - start_time + lock_ttl)`. Currently, it uses `DEFAULT_LOCK_TTL`, which doesn't make much sense.

**Comment by andylokandy** [comment]
@ekexium Is this solved?

**Comment by ekexium** [comment]
Not yet.

**Comment by andylokandy** [comment]
@TszKitLo40 Would you like to have a try?

**Comment by TszKitLo40** [comment]
> @TszKitLo40 Would you like to have a try?

I would like to.
