### ISSUE TITLE
In rpcclient the `raw_scan` requires bounds

### ISSUE THREAD

**Issue by Hoverbear** [tikv/client-rust#29]
In #25 we found we are taking `Option<_>` for start, but it must be set. So we can make it always take a value instead.

This can be resolved by changing ` src/rpc/tikv/client.rs`'s `raw_scan` function to accept `end_key` as `Key` instead of `Option<Key>`

**Comment by sticnarf** [comment]
Looking at the code in TiKV, I guess at least an empty end_key is supported? Not sure if a request without the start_key works.

**Comment by Hoverbear** [comment]
Got overzealous, thanks. :)

**Comment by nrc** [comment]
@Hoverbear looks like this can be closed then?
