### ISSUE TITLE
will the pessimistic locks be auto released when panicing?

### ISSUE THREAD

**Issue by gfreezy** [tikv/client-rust#314]

**Comment by ekexium** [comment]
No. I think we can hardly do anything when panicking. But locks should be rolled back if the operation fails. The task is part of #313

**Comment by gfreezy** [comment]
Will the locks be freed when the connection disconnects?

**Comment by ekexium** [comment]
> Will the locks be freed when the connection disconnects?

When you have network issues, the client can't release the locks. But the locks will expire and can be released when other transactions meet them.

**Comment by gfreezy** [comment]
Will the locks be released only when they expire? What is the default ttl when ttl is not set in the locking request?

**Comment by ekexium** [comment]
> Will the locks be released only when they expire? 

No. TiKV doesn't actively look for expired locks. They are only released if some other transaction meets them.

> What is the default ttl when ttl is not set in the locking request?

In client-rust it's defined by https://github.com/tikv/client-rust/blob/eb1d2da05cc857818e078bc3d91ce50343031642/src/transaction/transaction.rs#L868-L869
