### ISSUE TITLE
What we will do  since take_region_error in kvpro have been removed ?

### ISSUE THREAD

**Issue by inevity** [tikv/client-rust#322]
https://github.com/tikv/client-rust/blob/master/tikv-client-store/src/errors.rs:32 use the method.

**Comment by ekexium** [comment]
Where did you find that `take_region_error` has been removed?

**Comment by inevity** [comment]
See master on kvproto, grep return none.  this commit 820f463fe509cfe7d2f0ea387f408c1728487834 remove this.

**Comment by ekexium** [comment]
> See master on kvproto, grep return none.

The code is generated when building it. The `region_error` fields still exist.  BTW for backward compatibility fields should be hardly removed.

**Comment by inevity** [comment]
The field is still  exist, but the method have been removed . I will dig it why this code work

**Comment by ekexium** [comment]
Just build client-rust and you can see code is generated. It generates methods like `get_` `take_` `has_` for each field. 
You might be interested in https://github.com/tikv/protobuf-build

I'm closing it for now. Feel free to open it if you still have questions :).
