### ISSUE TITLE
use tikv client #rust with #grpcio 

### ISSUE THREAD

**Issue by linuxpham** [tikv/client-rust#325]
Hi admin,

I use `grpcio` to build `grpc` server. #client-rust use #tokio runtime, `grpcio` use another runtime.

How can I use `tikv-client` in RpcContext `grpcio` ?

Thank you!

**Comment by ekexium** [comment]
Did you mean tikv/grpc-rs?

tikv-client (for now, and at least in the near future) requires the tokio runtime. In my humble opinion, if the runtimes are incompatible, you'd better use them independently and choose an appropriate communication mechanism.

**Comment by Xuanwo** [comment]
Hi, the tikv-client has been migrated to `tonic`. Therefore, I believe that this issue is no longer valid. I will proceed to close this issue, but please feel free to reopen it if the problem persists.
