### ISSUE TITLE
Transaction Drop Behavior

### ISSUE THREAD

**Issue by Hoverbear** [tikv/client-rust#35]
As part of #15, one question to consider is how to handle it when a transaction is dropped?

Transaction *should* have `#[must_use]` on it to create a warning for users who might accidentally drop it, but in the case of something like `let _ = client.begin()` we should consider if it is appropriate to just drop the memory. Should we attempt to rollback?

**Comment by sunxiaoguang** [comment]
I think rollback is appropriate for this scenario. And that's what JDBC does.

> Note: When configuring a Connection, JDBC applications should use the appropriate Connection method such as setAutoCommit or setTransactionIsolation. Applications should not invoke SQL commands directly to change the connection's configuration when there is a JDBC method available. By default a Connection object is in auto-commit mode, which means that it automatically commits changes after executing each statement. If auto-commit mode has been disabled, the method commit must be called explicitly in order to commit changes; otherwise, database changes will not be saved.

**Comment by Hoverbear** [comment]
PTAL @sticnarf

**Comment by sticnarf** [comment]
The semantics should be rollback. And for optimistic transaction, no data is written to the database before the user commits the transaction. We needn't do anything for it.

**Comment by nrc** [comment]
Rust doesn't support async drop yet, so I don't think we can do anything that requires communication on drop, i.e., we can't rollback or commit.

What we could do is panic on drop if a transaction has not been rolled back or committed (we would need to add some kind of explicit 'abort' method in case the user wants to drop the transaction without committing/rolling back).
