### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by tobiemh** [tikv/client-rust#365]
Hi. I was wondering if there are any plans for publishing a new release at any time (which incorporates the changes from `grpcio-sys` crate).

Building the current `master` branch is far more reliable on many different platforms and when cross-compiling, and this would fix a number of issues when building a library which uses `tikv-client` dependency.

This is also related to #362

**Comment by ekexium** [comment]
Sounds reasonable.
Hi @nrc , could you help add me as owners of the crates?

**Comment by wfxr** [comment]
Same issue. Current version 0.1.0 cannot compile on latest archlinux. Can you help release a new version? @nrc @andylokandy @sunxiaoguang

**Comment by hamidrezakp** [comment]
Same issue here too.
Isn't there any new release coming out soon?

If there is some work required before release, I'd like to help.

**Comment by Xuanwo** [comment]
v0.2 has been released, please give it a try!
