### ISSUE TITLE
gRPC error: RpcFailure: 4-DEADLINE_EXCEEDED Deadline Exceeded

### ISSUE THREAD

**Issue by bxq2011hust** [tikv/client-rust#371]
I deploy a TiKV cluster which is consist of 3 TiKV and 3 PD without TiDB instance, and set `resource_control.memory_limit = 8G`. After a period of operation, I will often get `gRPC error: RpcFailure: 4-DEADLINE_EXCEEDED Deadline Exceeded` when committing secondary keys or getting KV from tikv, and the timeout of the request will be likely to last for some time. Why does this happen？Should I call the gc method of client or this is because of tikv resource limit?

**Comment by ekexium** [comment]
Well I can't tell the reason based on your information. And this is not the best place to discuss the usage of TiKV. Could you ask a question in AskTUG? You could also describe your workload/opeartions and had better provide the metrics of your cluster. I suppose someone there could help you.

**Comment by bxq2011hust** [comment]
> Well I can't tell the reason based on your information. And this is not the best place to discuss the usage of TiKV. Could you ask a question in AskTUG? You could also describe your workload/opeartions and had better provide the metrics of your cluster. I suppose someone there could help you.

ok, thanks
