### ISSUE TITLE
[Perfomance] The performance problem of scan method is slightly worse

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/client-rust#372]
Use the same KeyRange and count to scan the same tikv by client-go and client-rust
When scanning, there is a big difference in the time consumption between the two

**Comment by yongman** [comment]
There is already a pull request for scan optimization, https://github.com/tikv/client-rust/pull/368 you can test it if you want.

**Comment by guoxiangCN** [comment]
> There is already a pull request for scan optimization #368, you can test it if you want.

ok, i will try it. But why doesn't trust client provide an iter interface similar to goclient, which can iterate data incrementally. Scan must specify the number. It cannot completely traverse all the keys in a KeyRange. If count is very likely, oom?
