### ISSUE TITLE
Build error when use TiKV client as dependency on Windows

### ISSUE THREAD

**Issue by tsinan** [tikv/client-rust#379]
Hi, I'm trying to build a library (which uses tikv-client as a dependency) on Windows. But there has error like:

[dependencies]
....
tikv-client = "0.1.0"

---------------------------------------------

C:\Root\Git\inner> cargo run
   Compiling openssl-sys v0.9.79
error: failed to run custom build command for `openssl-sys v0.9.79`

Caused by:
  process didn't exit successfully: `C:\Root\inner\target\debug\build\openssl-sys-84a918e37cf2f10c\build-script-main` (exit code: 101)
  --- stdout
  running "perl" "./Configure" "--prefix=C:\\Root\\inner\\target\\debug\\build\\openssl-sys-a101f83f77a1f6dd\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\openssl-src-111.24.0+1.1.1s\src\lib.rs:496:39  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---------------------------------------------

How do I fix this, or where can I find documentation on using Tikv client for Windows? Thanks~

**Comment by Xuanwo** [comment]
Hi, we have migrated to `tonic` which may have better support for windows. Please reopen this issue if the problem presists.
