### ISSUE TITLE
with_atomic_for_cas for put delete

### ISSUE THREAD

**Issue by MohsenNz** [tikv/client-rust#383]
Why it is with_atomic_for_cas while we can use it for put and delete.
In the other word, dose it valid to use it for put/delete?
if yes, what dose means? because I thought all put and delete occur atomically on quorum of nodes.

**Comment by ekexium** [comment]
If you need CAS opertions, you need to set `with_atomic_for_cas`. It's explained in the doc of `with_atomic_for_cas`
