### ISSUE TITLE
Empty values in raw client

### ISSUE THREAD

**Issue by Snnappie** [tikv/client-rust#39]
I noticed the raw client considers it an error if you `put` (or `batch_put`) with an empty value. Is this required by tikv? And if not, can that restriction be removed from the client?

I have a need for writing empty values. I can work around this by just appending a `0x00` on every value, and stripping it out on read. But it would be nice to not have to do this.

**Comment by Hoverbear** [comment]
Hmmm, I don't know if this is permitted by TiKV... @breeswish do you know?

**Comment by Snnappie** [comment]
I dug through the TiKV code and think it isn't supported. I worked around it in my code, so we can close this. Thanks
