### ISSUE TITLE
build cpp client  depend on lastest client-rust 

### ISSUE THREAD

**Issue by Jay-ju** [tikv/client-rust#393]
【Issues】we need cpp static  lib，   but modify depencies about client-rust using newest commit， but build failed

【Detail】

Compiling grpcio v0.10.4
error[E0277]: the trait bound `raft_proto::prelude::Entry: prost::Message` is not satisfied
    --> /data00/code/community/pingcap/tikv_client-cpp/target/debug/build/tikv-client-proto-4a5c0e59aeb593bb/out/protos/raft_cmdpb.rs:273:28
     |
273  | #[derive(Clone, PartialEq, ::prost::Message)]
     |                            ^^^^^^^^^^^^^^^^ the trait `prost::Message` is not implemented for `raft_proto::prelude::Entry`
     |
     = help: the following other types implement trait `prost::Message`:
               ()
               Admin
               AdminRequest
               AdminResponse
               AllocIdRequest
               AllocIdResponse
               AlreadyExist
               AskBatchSplitRequest
             and 492 others
note: required by a bound in `message::encode`
    --> /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/prost-0.9.0/src/encoding.rs:1043:12
     |
1043 |         M: Message,
     |            ^^^^^^^ required by this bound in `encode`
     = note: this error originates in the derive macro `::prost::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `raft_proto::prelude::Entry: prost::Message` is not satisfied
    --> /data00/code/community/pingcap/tikv_client-cpp/target/debug/build/tikv-client-proto-4a5c0e59aeb593bb/out/protos/raft_cmdpb.rs:273:28

**Comment by Smityz** [comment]
fixed here https://github.com/tikv/client-cpp/pull/21
