### ISSUE TITLE
The rawkv scan performance of is severely degraded.

### ISSUE THREAD

**Issue by Smityz** [tikv/client-rust#398]
I put some data in my TiKV cluster(version v6.5.3), and test the performance between Rust SDK and Go SDK, and found a serious performance problem. 
I tried to scan the entire table with a limit of 1000 data per RPC and found that the delay per RPC for the Go SDK was 3ms while the delay for the Rust SDK was 200+ms. However, the server showed the same delay in both cases.
Another strange thing is that when testing with Rust, the server displays a scan QPS of 1000 while GoLang is around 500. It is obvious that the Rust SDK is performing abnormally in the test.
Here is my test code:
```rust
// run in release mode
#![type_length_limit = "8165158"]

mod common;

use std::time::Instant;

use crate::common::parse_args;
use tikv_client::{Config, IntoOwnedRange,Key,  RawClient as Client, Result};

#[tokio::main]
async fn main() -> Result<()> {
    // You can try running this example by passing your pd endpoints
    // (and SSL options if necessary) through command line arguments.
    let args = parse_args("raw");

    // Create a configuration to use for the example.
    // Optionally encrypt the traffic.
    let config = if let (Some(ca), Some(cert), Some(key)) = (args.ca, args.cert, args.key) {
        Config::default().with_security(ca, cert, key)
    } else {
        Config::default()
    };

    // When we first create a client we receive a `Connect` structure which must be resolved before
    // the client is actually connected and usable.
    let client = Client::new_with_config(args.pd, config, None).await?;
    let client = client.clone();

    let mut scan_range =("".."z").into_owned();  
    loop {
        let start = Instant::now();
        let pairs = client
            .scan(scan_range.clone(), 1000)
            .await
            .expect("Could not scan");
        println!("duration: {}", start.elapsed().as_millis());
        let keys: Vec<_> = pairs.into_iter().map(|p| p.key().clone()).collect();
        scan_range = (keys.last().unwrap().clone()..=String::from("z").clone().into()).into();
    }
}
```

```Golang
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/tikv/client-go/v2/config"
	"github.com/tikv/client-go/v2/rawkv"
)

func main() {
	cli, err := rawkv.NewClient(context.TODO(), []string{"127.0.0.1:2379"}, config.DefaultConfig().Security)
	if err != nil {
		panic(err)
	}
	defer cli.Close()
	startKey := ""
	endKey := "zzz"
	for {
		startTime := time.Now()
		k, _, err := cli.Scan(context.Background(), []byte(startKey), []byte(endKey), 1000)
		if err != nil {
			panic(err)
		}
		if len(k) == 0 {
			break
		}
		startKey = string(k[len(k)-1])
		fmt.Printf("time cost: %v\n", time.Since(startTime))
	}
}

```
Monitor:
![image](https://github.com/tikv/client-rust/assets/22953824/669f6a9d-ffac-4af3-a815-1b2b7b06077a)

**Comment by andylokandy** [comment]
I am unable to replicate the issue on version 7.3.0. Could you please retest using a different version?

**Comment by Smityz** [comment]
Yes, you need to put a large amount of data, such as 10GB, into your test cluster to discover a significant increase in latency.

**Comment by Smityz** [comment]
And the cause I found here
https://github.com/tikv/client-rust/blob/2c831bac149bd41760ac2aa2e31672319d6fb79d/src/pd/client.rs#L127-L134
The `limit` parameter does not limit the number of rows in a region. If the scanning range is the entire table, every scan will go through the entire table, regardless of the `limit` parameter.
You can delete this line to verify
https://github.com/tikv/client-rust/blob/2c831bac149bd41760ac2aa2e31672319d6fb79d/src/raw/client.rs#L602

**Comment by Smityz** [comment]
The simplest solution is to limit a scan RPC to only scan data within a single region.
