### ISSUE TITLE
Cant run two consecutive transactions

### ISSUE THREAD

**Issue by lveillard** [tikv/client-rust#416]
For some reason adding a second transaction generates an error all the time:

```
use tikv_client::{Error, TransactionClient};

async fn run() -> Result<(), Error> {
    let txn_client = TransactionClient::new(vec!["127.0.0.1:2379"]).await?;

    let mut txn2 = txn_client.begin_optimistic().await?;
    txn2.put("k1".to_owned(), "v1".to_owned()).await?;
    txn2.put("k2".to_owned(), "v2".to_owned()).await?;
    txn2.put("k3".to_owned(), "v3".to_owned()).await?;
    txn2.put("k4".to_owned(), "v4".to_owned()).await?;
    txn2.commit().await?;
    
    let limit = 1000;
    let mut txn3 = txn_client.begin_optimistic().await?;
    let result = txn2.scan("k1".to_owned().."k5".to_owned(), limit).await?;
    result.for_each(|pair| println!("{:?}", pair));
    txn3.commit().await?;

    Ok(())
}

#[tokio::main]
async fn main() {
    run().await.unwrap();
}

```

Throws this error:
`thread 'main' panicked at 'Dropping an active transaction. 
Consider commit or rollback it.`

I don't know if I'm doing something weird, but it seems like both txn are commited so if i'm doing something wrong maybe the error message is not the most adapted to the error i'm generating?

**Comment by pingyu** [comment]
> let result = txn2.scan("k1".to_owned().."k5".to_owned(), limit).await?;

I guess `txn2` here should be `txn3` ?

**Comment by lveillard** [comment]
> > let result = txn2.scan("k1".to_owned().."k5".to_owned(), limit).await?;
> 
> I guess `txn2` here should be `txn3` ?

Hello! Thanks for the answer :)

Yes, it was a test to see if that was the cause, but it happens with all tx3.

I feel like it happens on txn without mutations (only reads)

For instance this one works:

```rust
use tikv_client::{Error, TransactionClient};

async fn run() -> Result<(), Error> {
    let txn_client = TransactionClient::new(vec!["127.0.0.1:2379"]).await?;

    let mut txn2 = txn_client.begin_optimistic().await?;
    txn2.put("k1".to_owned(), "v1".to_owned()).await?;
    txn2.put("k2".to_owned(), "v2".to_owned()).await?;
    txn2.put("k3".to_owned(), "v3".to_owned()).await?;
    txn2.put("k4".to_owned(), "v4".to_owned()).await?;
    txn2.commit().await?;
    

    Ok(())
}

#[tokio::main]
async fn main() {
    run().await.unwrap();
}
```

But this one doesnt:
```rust
use tikv_client::{Error, TransactionClient};

async fn run() -> Result<(), Error> {
    let txn_client = TransactionClient::new(vec!["127.0.0.1:2379"]).await?;

    let limit = 1000;
    let mut txn3 = txn_client.begin_optimistic().await?;
    let result = txn3.scan("k1".to_owned().."k5".to_owned(), limit).await?;
    result.for_each(|pair| println!("{:?}", pair));
    txn3.commit().await?;

    Ok(())
}

#[tokio::main]
async fn main() {
    run().await.unwrap();
}
```

**Comment by pingyu** [comment]
I'm sorry for the late.

> I feel like it happens on txn without mutations (only reads)

I think yes, and it should be a bug.

When mutations is empty, [`Transaction.commit()`](https://github.com/tikv/client-rust/blob/dd34500282353d910bdc57c0282fe6ca602c1b90/src/transaction/transaction.rs#L650) return without set the status to `TransactionStatus::Committed`, which cause the panic.

To work around this issue, you can create a [`Snapshot`](https://github.com/tikv/client-rust/blob/dd34500282353d910bdc57c0282fe6ca602c1b90/src/transaction/client.rs#L211), then invoke [`scan`](https://github.com/tikv/client-rust/blob/dd34500282353d910bdc57c0282fe6ca602c1b90/src/transaction/snapshot.rs#L52) on it.

**Comment by pingyu** [comment]
Close for inactive. Please reopen the pull request whenever you need any further help. Thanks~
