### ISSUE TITLE
perf comparision between tikv golang client and client-rust?

### ISSUE THREAD

**Issue by inevity** [tikv/client-rust#421]
Anyone have perform this?
We found client-rust perf worse than the golang client on raw tikv doing set ops(6w vs 27w iops) , so now just the go client through ffi.

What are your data?
I saw [fix raw scan](https://github.com/tikv/client-rust/pull/409) fix on scan perf.
And these days we did not have the region cache in the client-rust.

**Comment by pingyu** [comment]
Can you share your benchmark program, workload, and cluster setup ? Thanks.

p.s. we have region cache [here](https://github.com/tikv/client-rust/blob/5ac72f2c32139f820a74bc8ca785677e3a3f1e81/src/pd/client.rs#L225).

**Comment by pingyu** [comment]
Close for inactive. Please reopen the pull request whenever you have further comments. Thanks~
