### ISSUE TITLE
test: IT fail after change cargo test to cargo nextest

### ISSUE THREAD

**Issue by ben1009** [tikv/client-rust#423]
IT may have concurrency issue, after change test to nextest, can [not passed](https://github.com/tikv/client-rust/actions/runs/6195615449/job/16823427863?pr=422) IT, but rollback to cargo test could [pass](https://github.com/tikv/client-rust/actions/runs/6217937945?pr=422)

```
------------
     Summary [   5.669s] 3/24 tests run: 0 passed, 3 failed, 38 skipped
        FAIL [   2.422s] tikv-client::failpoint_tests txn_cleanup_2pc_locks
        FAIL [   2.616s] tikv-client::failpoint_tests txn_cleanup_async_commit_locks
        FAIL [   3.246s] tikv-client::failpoint_tests txn_cleanup_locks_batch_size
error: test run failed
make: *** [Makefile:26: integration-test] Error 100
Error: Process completed with exit code 2.
```

**Comment by pingyu** [comment]
Currently IT cases are running on the same real TiKV cluster. So they would be conflict with each other if running concurrently.

At the beginning of each case, it will [clear the TiKV](https://github.com/tikv/client-rust/blob/5ac72f2c32139f820a74bc8ca785677e3a3f1e81/tests/common/mod.rs#L26) to address the conflicts.

It's not possible to run IT cases concurrently by now. Maybe we can utilize [`multi-tenancy`](https://github.com/tikv/client-rust/pull/353) to isolate the test case in the future.

**Comment by ben1009** [comment]
close for now, since the behaviour is kind of by design
