### ISSUE TITLE
why remove the mock-tikv?

### ISSUE THREAD

**Issue by inevity** [tikv/client-rust#426]
@andylokandy  saw [Migrate to tonic](https://github.com/tikv/client-rust/commit/0a1de19450b178378132b865a13adbee860e774f) remove the mock-tikv. 
The mock-tikv is useless? or  when migrate to tonic, no need mock-tikv? or you have another impl?

**Comment by andylokandy** [comment]
> The mock-tikv is useless.

Yes. the mock-tikv in client-rust is very incomplete and is not used.
