### ISSUE TITLE
Using regular expression in `trim_start_matches`

### ISSUE THREAD

**Issue by ice1000** [tikv/client-rust#43]
Can we use a regex here? Like `https?://`

https://github.com/tikv/client-rust/pull/40#discussion-diff-281319147R81

_Originally posted by @ice1000 in https://github.com/tikv/client-rust/pull/40_

**Comment by hello2dj** [comment]
Use regex library?

**Comment by hello2dj** [comment]
use regex library?

**Comment by hello2dj** [comment]
see this pr: https://github.com/tikv/client-rust/pull/52

**Comment by ice1000** [comment]
Fixed in #52
