### ISSUE TITLE
Unable to run starter example code

### ISSUE THREAD

**Issue by andrewvious** [tikv/client-rust#449]
I'm following the guide directly from here:
https://tikv.org/docs/3.0/tasks/try/docker-stack/

I follow all the steps, 
running `docker service ls` as shown in the example it gives:

```
ID             NAME        MODE         REPLICAS   IMAGE                 PORTS
qful949umrik   tikv_pd     replicated   0/1        pingcap/pd:latest     *:2379-2380->2379-2380/tcp
73uejutp8h3h   tikv_tikv   replicated   0/1        pingcap/tikv:latest   *:20160->20160/tcp
```

where in the example `replicated` shows `1/1` for both.

When it came to building the image I had to update `nightly` in `rust-toolchain.toml` and add `openssl` to deps in the `tikv-example` to even get the image to be created. 

Now for the final command `docker run -ti --rm --network tikv tikv-example` it gives me an error: 
```
Error: InternalError { message: "[//builder/.cargo/git/checkouts/client-rust-5a1ccd35a54db20f/c6110dd/src/pd/cluster.rs:209]: PD cluster failed to respond" }
```
I am on an M1 Mac

**Comment by pingyu** [comment]
When `REPLICAS` is `0/1`, the PD & TiKV was not started normally. The docs of v3.0 would be out-of-date.

Please try to start a TiKV cluster by TiUP. See https://github.com/tikv/client-rust?tab=readme-ov-file#building-and-testing.
