### ISSUE TITLE
`raw_batch_scan` unimplemented

### ISSUE THREAD

**Issue by Snnappie** [tikv/client-rust#48]
I have a hacky implementation on [this branch](https://github.com/Snnappie/client-rust/tree/snnappie-dev). It also changes the API from returning a flattened `Vec<KvPair>` to `Vec<Vec<KvPair>>` (which adds to the "hackiness" because TiKV returns it as a flattened vector).
This fit my particular use case better, but I'm not sure it is desirable in general.

Are there plans to implement this feature? I could clean up my implementation and open a pull request.

**Comment by Hoverbear** [comment]
Hi! Yes, we'd love to merge this feature. Going through some review might also help improve the code's hackiness! 

We do want to try to fit your use case, can you open an issue about it?

Do you think the PR could use a TiKV-faithful representation? :)

**Comment by ekexium** [comment]
I'm gonna close this since #134 implemented raw_batch_scan. It returns a flattened result. Feel free to file a new issue if it doesn't fit your needs.
