### ISSUE TITLE
Is the PdReactor's StreamingCallSink properly cancelled? 

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#54]
In the futures 0.1 versionof the client, in `PdReactor::init` in src/rpc/pd/leader.rs, we called `sender.get_mut().get_ref().cancel()`. However, after migrating to futures 0.3 (https://github.com/tikv/client-rust/pull/41), we can't get mutable access to the underlying `StreamingCallSink` to call cancel. I think that the `StreamingCallSink` will be cancelled when `_sender` is dropped, but I could not confirm this.

**Comment by sticnarf** [comment]
The old implementation is removed. We don't need to care about it any more. :)
