### ISSUE TITLE
Key and Value should be coercible from &[u8]

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#61]
Since we can coerce from both `Vec<u8>` and `&str`. This will require some new `From` impls in kv.rs.

**Comment by Hoverbear** [comment]
Notably, we only allow `&'static str` as it's commonly used in examples. We don't want to add more implicit copying than that! We did have some discussion about a possible `KeyRef` or `ValueRef` type though to avoid a copy.

**Comment by nrc** [comment]
> Notably, we only allow &'static str as it's commonly used in examples

Yikes! I hadn't noticed that. That seems somewhat surprising. Maybe it is better to remove that and do something explicit in the examples (I agree that ideally we shouldn't do implicit allocation).

> KeyRef or ValueRef type

sgtm

**Comment by Hoverbear** [comment]
Unfortunately it makes the examples *so* nice. :( We do talk about it in the documentation.

**Comment by nrc** [comment]
> Unfortunately it makes the examples so nice.

The Ref types? Or making the str conversion explicit?

**Comment by Hoverbear** [comment]
Being able to `impl Into<Key> for &'static str`. Means the examples are almost noiseless.

**Comment by nrc** [comment]
So I've been thinking about this and playing around with a `KeyRef` type. `KeyRef` does make things a bit nicer, at the expense of making the code a bit more complex, but I think fundamentally we have two conflicting goals: we want to avoid implicit allocation of keys and we want to avoid any explicit overhead in the examples. The way we do this at the moment is to carve out a special exception for `&'static str` which I think causes more trouble than it saves: anybody following the examples who then tries to generalise is going to get some really unhelpful error messages.

Note that in theory we could avoid copying or allocating with static borrowed keys up to serialisation, but in practice we allocate for and copy the static keys, so we're just bending the rules for examples, not being smart.

I see a few ways forward:

1. keep the current workaround (at least adding a similar thing for `&'static [u8]` so byte string literals also work). I don't like this as outlined above.
2. Remove the Into<Key> impls for borrowed types. This requires the user to use `to_owned` which makes the examples a bit noisier, but more realistic. It is nice and simple.
3. Use `Cow` and `KeyRef` this means we do no *unnecessary* allocations/copies. If the user passes a reference we must clone it somewhere, but if the user had to pass the reference then they would have had to clone it, so this is performance neutral. It is more consistent because it applies to borrowed references with all lifetimes, not just `'static`. Examples don't get any noisier. However, it adds considerable code complexity (not just in the key/value API, but inside the clients).
4. We treat `'static` types specially all the way through to serialisation. We'd have to create a `StaticCow` type to do this. We could then take any types which don't need allocation/copying, but not those that would require it (i.e., non-static references). Examples are quiet, but we do have a minor inconsistency that moving from a static to non-static lifetime means we get an error (and not a helpful one; in general, Rust APIs try to avoid this). This should in theory improve performance in a small number of cases. This is the only solution I haven't partially implemented, so there are more unknowns. It is the most complex solution because it requires the most new types and introduce abstraction throughtout the client, not just in the surface API.

My inclination is towards one of the middle two - both are fairly performant, consistent, and not too complex. 3 is more ergonomic (especially for examples), but 2 has a simpler (and perhaps less surprising) API.

**Comment by Hoverbear** [comment]
@nrc The whole goal of implementing `&'static [u8]` was to reduce complexity. :) Let's not make it more complex to enable it. I'd rather pollute the examples with some `to_bytes()` instead of add a bunch of complexity.
