### ISSUE TITLE
Allow building integration tests without running them

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#69]
As an alternative, we could check for the `PD_ADDR` env var and pass the test if it is not present (or ignore it if it is not present at compile time?).

My reasoning is that when working on the library, it is nice to check that the integration tests still compile, even if we don't run them. Given we don't run them by default today, I don't think passing by default will give a false sense of security.

@Hoverbear what do you think?

**Comment by Hoverbear** [comment]
Is it possible to do `no-run` on tests based on feature flags? Maybe we could use this feature to just enable running the tests?

**Comment by nrc** [comment]
> Is it possible to do no-run on tests based on feature flags? Maybe we could use this feature to just enable running the tests (not building of them, which is always)?

Good question! I think it should be possible, just a `cfg_attr` and that would be a good solution if it works.

**Comment by Hoverbear** [comment]
Hmmm let me try it!

**Comment by Hoverbear** [comment]
@nrc If we still require `property-testing` feature is that ok? Unfortunately due to the `proptest` macro it's difficult to include it in the build without that feature.

**Comment by nrc** [comment]
moving discussion to #68 since I'm finding it difficult to flick between tabs :-)
