### ISSUE TITLE
Should we allow empty values?

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#75]
cc https://github.com/tikv/client-rust/issues/39

They are not permitted to be stored in TiKV, so we could prevent them ever being created. I'm not sure if TiKV ever returns them.

I'm not sure how to make this ergonomic - we could dynamically check easily enough, but a panic is not very friendly (especially if it is not the user's fault), but returning `Result` from every function which creates a `Value` is not great either.

**Comment by Hoverbear** [comment]
Perhaps we can check them at the request boundary instead of the creation boundary?
