### ISSUE TITLE
Is `ColumnFamily::default()` reasonable?

### ISSUE THREAD

**Issue by Hoverbear** [tikv/client-rust#9]
In `raw::Client` based requests there is an optional `cf(...)` value. Most requests contain a `Option<ColumnFamily>`. Since by default requests should be for the default `ColumnFamily` we may be able to `impl Default for ColumnFamily` and only hold a `ColumnFamily` instead.

**Comment by Hoverbear** [comment]
Refactoring has made this obselete.

**Comment by Kerollmops** [comment]
I have a little question about column families, is it / will it be possible to create a new column family with the Client?

**Comment by sunxiaoguang** [comment]
> I have a little question about column families, is it / will it be possible to create a new column family with the Client? Currently it is only possible to specify the "default" one.

It is not possible to use arbitrary column family at this time. TiKV prohibits column families that it knows, which are hard coded at this time. This may change in the future.

**Comment by Kerollmops** [comment]
Ok, thank you!

So currently, a possible work around is to prefix every keys by the column-family name? This is not the job of this client, obviously.

**Comment by nrc** [comment]
The client currently allows any column family to be specified using just a string.

In any case, this issue is not really relevant any more, so closing.
