### ISSUE TITLE
Deciding whether a key exists by the value's emptiness is inaccurate

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-rust#99]
It is actually possible and reasonable to put an empty value into TiKV. Then, we cannot distinguish an empty value from a non-existent key.

After https://github.com/tikv/tikv/pull/5240, TiKV returns `not_found` field in raw_get and kv_get. Then, we can rely on this field to decide whether the key exists. However, there is a problem that this change is not backported to TiKV release 3.0.

Before the next major release of TiKV comes out, `BatchGet` may be a good alternative. Non-existent keys are not included in the returned pair array. And after the next major release of TiKV,  maybe we can release a new version of this client which allows breaking changes (like 0.1 to 0.2), and switch to using the point get APIs.

**Comment by ekexium** [comment]
Both raw get and transactional get now use this field. We can close it if we only intend to support TiKV 4.0 or newer versions.

**Comment by nrc** [comment]
> Both raw get and transactional get now use this field. We can close it if we only intend to support TiKV 4.0 or newer versions

Do we use the field in the client, or do we need to make that change?

**Comment by ekexium** [comment]
> > Both raw get and transactional get now use this field. We can close it if we only intend to support TiKV 4.0 or newer versions
> 
> Do we use the field in the client, or do we need to make that change?

We already used them.
https://github.com/tikv/client-rust/blob/c7eeff9e4a5a5aae75ac33d4d46f4cedbb62b6ff/src/raw/requests.rs#L42-L46
https://github.com/tikv/client-rust/blob/c7eeff9e4a5a5aae75ac33d4d46f4cedbb62b6ff/src/transaction/requests.rs#L39-L43
